### PR TITLE
2023.07.21

### PR DESCRIPTION
**Pull request by desertwitch**
- fix: persist config files when rebooting
- new: implement lowbatt event fail-safe in settings
- new: always pull-in latest config files on reinstall/upgrade
- new: implement battery replacement notification in settings

details: https://forums.unraid.net/topic/60217-plugin-nut-v2-network-ups-tools/?do=findComment&comment=1285056

### CODE REVIEW

**Comment by SimonFair** [comment]
Hi thanks for the changes. In the plg you are removing user configs. I tend not to remove configs so they are still there if the user wants to restore. I will look to create a package this weekend.

**Comment by desertwitch** [comment]
Hi, thanks for checking. It doesn't remove the user configuration file (nut.cfg). It only removes the auto-populated NUT daemon files (within _/etc/nut/_ and backed up to _PLGPATH/ups_ to survive reboots) when uninstalling.

This happens so that future changes to those files in newer versions of the plugin can be applied correctly when upgrading or reinstalling the plugin. If this removal were not to happen, reinstalling the script would always pull the old (backed up) versions of the NUT daemon files from the flash drive into _/etc/nut_ instead of the newer versions (with new features/new changes) from the package. **The user-configured settings from the web interface are of course not deleted and are kept for later re-installing.**

**Comment by SimonFair** [comment]
I have released your changes as 2023.07.22 thanks again.

**Comment by SimonFair** [comment]
I have noticed on booting I see cp messages on the console saying not replacing can we redirect to  /dev/null

**Comment by desertwitch** [comment]
> I have noticed on booting I see cp messages on the console saying not replacing can we redirect to /dev/null

sure, added in #10

**Pull request merged**
