### PR TITLE
2023.07.26

### PR DESCRIPTION
**Pull request by desertwitch**
- **fix:** reduce console spam of copy operations by redirecting output to /dev/null, as requested in https://github.com/SimonFair/NUT-unRAID/pull/3#issuecomment-1649094177

- **fix:** stop services before a plugin upgrade on the live system to remove any file locks preventing files from getting patched on the running instance. a reboot should now no longer be required for all changes to become active.

- **fix:** old installation remnants cause updating or transitioning to another nut package on running instance to fail

- **fix:** fix a permissions issue causing some drivers in 2.8.0 not to have access to their required folders

- **new:** add button for users to be able to save their UPS details into a dummy-ups compliant diagnostics file
this file can then be uploaded on the forums and given to the developers in case problems with the plugin arise
thanks to @Peuuuur-Noel for the improvements to the privacy of the exported files (removing serial, macaddr)

### CODE REVIEW

**Comment by desertwitch** [comment]
tested working 6.12.3

**Comment by desertwitch** [comment]
tested working 6.12.3 (ready to merge)

**Comment by desertwitch** [comment]
tested working 6.12.3 (ready to merge)

**Comment by desertwitch** [comment]
not ready to merge (fixing bug at the moment)

**Comment by desertwitch** [comment]
tested working (6.12.3) - ready to merge at long last

**Comment by SimonFair** [comment]
If I merge one and the other one could there be cross over? Which one do we want to do first? #12 or this one? Please can we make PRs draft until ready to merge?

**Comment by desertwitch** [comment]
#12 first, no crossovers to be expected
sorry about the many commits, wasn't expected 
will draft more before starting a pull request in the future

**Comment by SimonFair** [comment]
Thanks, do you want me to merge 12 and then release a package? Then do 13 and release?

**Comment by desertwitch** [comment]
I think you can merge both and then done a single release, doesn't require separate releases.

**Comment by desertwitch** [comment]
I'll resolve the conflict in around 10 minutes, if you can wait with the release you can release all changes inside one release.

**Comment by desertwitch** [comment]
Thanks, all good now, sorry about the trouble!

**Comment by SimonFair** [comment]
Thanks for your efforts not a problem.

**Comment by SimonFair** [comment]
Released 2023.07.26

**Pull request merged**
